{{- $fullName := include "openconductor.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "openconductor.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.global.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
