{{- $fullName := include "seobuilder.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-server
  labels:
    {{- include "seobuilder.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector: 
  {{- include "seobuilder.labels" . | nindent 6 }}
