{{- $fullName := include "seobuilder.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-worker
  labels:
    {{- include "seobuilder.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "seobuilder.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "seobuilder.labels" . | nindent 8}}
      annotations:
        commit_sha: {{ .Values.global.commit }}
    spec:
      imagePullSecrets:
      - name: restack-ecr
      containers:
      - name: {{ $fullName }}-container
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: Always
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false

        envFrom:
          - configMapRef:
              name: {{ $fullName }}
          - secretRef:
              name: {{ $fullName }}
        
        {{- if .Values.resources }}
        resources: 
        {{- toYaml .Values.worker.resources | nindent 10 }}
        {{- end }}
        
      # nodeSelector:
      # affinity:
      # tolerations:

